namespace MiningGame.Core.Models
{
    public class Character
    {
        public string Name { get; set; }
        public int Stamina { get; private set; }
        public int MaxStamina { get; private set; }
        public int Power { get; private set; }
        public double MovementSpeed { get; private set; }
        public int BombRange { get; private set; }
        public int BombAmmo { get; private set; }
        public double BombCooldown { get; private set; }
        public bool IsBombOnCooldown => DateTime.UtcNow < _lastBombTime + _bombCooldown; // Thread-safe cooldown check
        public Dictionary<string, bool> SpecialAbilities { get; private set; }
        public int PositionX { get; set; }
        public int PositionY { get; set; }

        private DateTime _lastBombTime;
        private readonly TimeSpan _bombCooldown;

        public Character(string name, int maxStamina, int power, double movementSpeed, int bombRange, int bombAmmo, double bombCooldown)
        {
            Name = name;
            MaxStamina = maxStamina;
            Stamina = maxStamina;
            Power = power;
            MovementSpeed = movementSpeed;
            BombRange = bombRange;
            BombAmmo = bombAmmo;
            BombCooldown = bombCooldown;
            _bombCooldown = TimeSpan.FromSeconds(bombCooldown);
            SpecialAbilities = new Dictionary<string, bool>();
        }

        /// <summary>
        /// Uses a bomb, reducing stamina and triggering cooldown if applicable.
        /// </summary>
        public void UseBomb()
        {
            if (Stamina <= 0)
                throw new InvalidOperationException("Not enough stamina to use a bomb!");
            if (IsBombOnCooldown)
                throw new InvalidOperationException("Bomb is still on cooldown!");

            Stamina--;
            _lastBombTime = DateTime.UtcNow;
            Console.WriteLine("Bomb used successfully. Cooldown started.");
        }

        /// <summary>
        /// Regenerates stamina by a percentage of the max stamina.
        /// </summary>
        public void RegenerateStamina()
        {
            int regenAmount = MaxStamina / 2; // Regenerate 50% of max stamina
            Stamina = Math.Min(Stamina + regenAmount, MaxStamina);
            Console.WriteLine($"Stamina regenerated by {regenAmount}. Current stamina: {Stamina}/{MaxStamina}");
        }

        /// <summary>
        /// Adds or activates a special ability.
        /// </summary>
        public void AddSpecialAbility(string abilityName)
        {
            if (!SpecialAbilities.ContainsKey(abilityName))
                SpecialAbilities[abilityName] = true;
            Console.WriteLine($"Special ability '{abilityName}' added.");
        }

        /// <summary>
        /// Checks if a special ability is active.
        /// </summary>
        public bool HasSpecialAbility(string abilityName)
        {
            return SpecialAbilities.ContainsKey(abilityName) && SpecialAbilities[abilityName];
        }
    }
}
